language: erlang

#script: rebar3 eunit
#install: true
script:
    - wget https://github.com/erlang/rebar3/releases/download/3.11.1/rebar3 && chmod +x rebar3 && ./rebar3 update
    - ./rebar3 do compile, eunit

otp_release:
  - 22.0.2
  - 21.0
  - 20.3
  - 19.3
